import type { MissionDefinition, SurvivalMapDefinition } from "../../core/types/content";

const urbanObstacles = [
  { x: 0, z: -12, width: 14, depth: 3, height: 3.5 },
  { x: -16, z: 8, width: 5, depth: 18, height: 3.5 },
  { x: 18, z: 4, width: 6, depth: 16, height: 3.5 },
  { x: -2, z: 22, width: 22, depth: 4, height: 3.5 },
  { x: 11, z: -28, width: 8, depth: 8, height: 4.2 },
];

const dockBreachObstacles = [
  { x: -12, z: 22, width: 10, depth: 5, height: 3.4 },
  { x: 8, z: 19, width: 8, depth: 5, height: 3.4 },
  { x: -16, z: 8, width: 5, depth: 18, height: 3.5 },
  { x: 18, z: 4, width: 6, depth: 16, height: 3.5 },
  { x: 2, z: -12, width: 12, depth: 3, height: 3.5 },
  { x: 11, z: -28, width: 8, depth: 8, height: 4.2 },
  { x: -5, z: -24, width: 6, depth: 9, height: 3.8 },
];

const industrialObstacles = [
  { x: -20, z: -4, width: 8, depth: 20, height: 4 },
  { x: 0, z: 12, width: 16, depth: 4, height: 5 },
  { x: 20, z: -6, width: 8, depth: 20, height: 4 },
  { x: 0, z: -24, width: 26, depth: 4, height: 5 },
  { x: 0, z: 28, width: 18, depth: 4, height: 5 },
];

const bunkerObstacles = [
  { x: -18, z: 0, width: 6, depth: 26, height: 4 },
  { x: 18, z: 0, width: 6, depth: 26, height: 4 },
  { x: 0, z: -16, width: 18, depth: 5, height: 4 },
  { x: 0, z: 12, width: 18, depth: 5, height: 4 },
  { x: 0, z: 36, width: 24, depth: 5, height: 4 },
];

export const campaignMissions: MissionDefinition[] = [
  {
    id: "dock-breach",
    name: "Dock Breach",
    theme: "urban",
    description: "Punch through a waterfront stronghold and restore access to the city grid.",
    narrative: "Open the floodgate route, break the defense ring, and exfil through the container lane.",
    recommendedRank: 1,
    rewards: { xp: 220, credits: 160 },
    playerSpawn: { x: 0, z: 32 },
    extractPoint: { x: 26, z: -34 },
    mapSize: { width: 70, depth: 90 },
    obstacles: dockBreachObstacles,
    enemySpawns: {
      alpha: [
        { x: 0, z: 16, enemyId: "rifleman" },
        { x: 10, z: 14, enemyId: "rifleman" },
        { x: -8, z: 10, enemyId: "rusher" },
      ],
      beta: [
        { x: 12, z: -4, enemyId: "marksman" },
        { x: -2, z: -6, enemyId: "rifleman" },
        { x: 16, z: -12, enemyId: "shield-heavy" },
      ],
      gamma: [
        { x: 22, z: -28, enemyId: "rifleman" },
        { x: 28, z: -18, enemyId: "marksman" },
        { x: 24, z: -24, enemyId: "rusher" },
      ],
    },
    objectives: [
      {
        id: "alpha",
        kind: "clear-zone",
        label: "Secure the checkpoint",
        description: "Clear the dock entrance and open a path forward.",
        zone: { x: 2, z: 12 },
        radius: 12,
        spawnIds: ["alpha"],
      },
      {
        id: "uplink",
        kind: "interact",
        label: "Restore grid uplink",
        description: "Hold interact at the terminal to bring the docks online.",
        zone: { x: 11, z: -10 },
        radius: 4,
        holdSeconds: 2,
        spawnIds: ["beta"],
      },
      {
        id: "extract",
        kind: "extract",
        label: "Extract through the floodgate lane",
        description: "Move to the extraction corridor and survive the exit push.",
        zone: { x: 26, z: -34 },
        radius: 5,
        spawnIds: ["gamma"],
      },
    ],
  },
  {
    id: "foundry-blackout",
    name: "Foundry Blackout",
    theme: "industrial",
    description: "Sabotage the foundry power chain and eliminate the site commander.",
    narrative: "Plant charges across the foundry floor before confronting Commander Helix in the furnace hall.",
    recommendedRank: 2,
    unlockMissionId: "dock-breach",
    rewards: { xp: 360, credits: 240 },
    playerSpawn: { x: 0, z: 34 },
    extractPoint: { x: 0, z: -34 },
    mapSize: { width: 78, depth: 92 },
    obstacles: industrialObstacles,
    enemySpawns: {
      "charge-a": [
        { x: -18, z: 18, enemyId: "rifleman" },
        { x: -25, z: 10, enemyId: "rusher" },
      ],
      "charge-b": [
        { x: 0, z: 4, enemyId: "marksman" },
        { x: 10, z: -2, enemyId: "rifleman" },
        { x: -10, z: -2, enemyId: "rifleman" },
      ],
      commander: [
        { x: 0, z: -22, enemyId: "boss-commander" },
        { x: -10, z: -18, enemyId: "rusher" },
        { x: 10, z: -18, enemyId: "shield-heavy" },
      ],
    },
    objectives: [
      {
        id: "charge-a",
        kind: "destroy-targets",
        label: "Destroy coolant relay A",
        description: "Place explosive force on the exterior relay.",
        zone: { x: -22, z: 12 },
        radius: 6,
        targetCount: 1,
        spawnIds: ["charge-a"],
      },
      {
        id: "charge-b",
        kind: "destroy-targets",
        label: "Destroy coolant relay B",
        description: "Collapse the center power route.",
        zone: { x: 0, z: 0 },
        radius: 8,
        targetCount: 1,
        spawnIds: ["charge-b"],
      },
      {
        id: "boss",
        kind: "boss",
        label: "Eliminate Commander Helix",
        description: "Break the command cell before it can reorganize the site.",
        zone: { x: 0, z: -22 },
        radius: 10,
        bossId: "commander-helix",
        spawnIds: ["commander"],
      },
      {
        id: "extract",
        kind: "extract",
        label: "Escape through the freight tunnel",
        description: "Reach the tunnel while the plant burns behind you.",
        zone: { x: 0, z: -34 },
        radius: 5,
      },
    ],
  },
  {
    id: "glassline",
    name: "Glassline",
    theme: "urban",
    description: "Push across the skyline relay district and hold the uplink until data exfil completes.",
    narrative: "Climb the relay boulevard, secure the rooftop relay, and survive the extraction window.",
    recommendedRank: 3,
    unlockMissionId: "foundry-blackout",
    rewards: { xp: 480, credits: 320 },
    playerSpawn: { x: -26, z: 28 },
    extractPoint: { x: 26, z: -26 },
    mapSize: { width: 90, depth: 84 },
    obstacles: [
      ...urbanObstacles,
      { x: -24, z: 12, width: 4, depth: 22, height: 4 },
      { x: 24, z: -10, width: 4, depth: 22, height: 4 },
    ],
    enemySpawns: {
      street: [
        { x: -14, z: 16, enemyId: "rusher" },
        { x: -6, z: 10, enemyId: "rifleman" },
        { x: 6, z: 8, enemyId: "marksman" },
      ],
      relay: [
        { x: 10, z: -6, enemyId: "shield-heavy" },
        { x: 18, z: -4, enemyId: "rifleman" },
        { x: 20, z: -14, enemyId: "marksman" },
      ],
      counter: [
        { x: 18, z: -20, enemyId: "juggernaut" },
        { x: 26, z: -14, enemyId: "rusher" },
        { x: 26, z: -24, enemyId: "rifleman" },
      ],
    },
    objectives: [
      {
        id: "street",
        kind: "clear-zone",
        label: "Break the boulevard line",
        description: "Open the street approach and deny the first defense ring.",
        zone: { x: -6, z: 12 },
        radius: 12,
        spawnIds: ["street"],
      },
      {
        id: "relay",
        kind: "hold",
        label: "Hold the relay uplink",
        description: "Stay in range while the relay copies the target package.",
        zone: { x: 12, z: -8 },
        radius: 7,
        holdSeconds: 12,
        spawnIds: ["relay"],
      },
      {
        id: "extract",
        kind: "extract",
        label: "Survive the counter-push and extract",
        description: "Fight through the response team and reach the evac point.",
        zone: { x: 26, z: -26 },
        radius: 5,
        spawnIds: ["counter"],
      },
    ],
  },
  {
    id: "iron-vault",
    name: "Iron Vault",
    theme: "bunker",
    description: "Assault the underground vault and end the siege program at its core.",
    narrative: "Drive through the bunker chambers, seize the reactor room, and destroy the Siege Breaker.",
    recommendedRank: 4,
    unlockMissionId: "glassline",
    rewards: { xp: 720, credits: 520 },
    playerSpawn: { x: 0, z: 42 },
    extractPoint: { x: 0, z: -40 },
    mapSize: { width: 84, depth: 112 },
    obstacles: bunkerObstacles,
    enemySpawns: {
      breach: [
        { x: -10, z: 24, enemyId: "shield-heavy" },
        { x: 10, z: 24, enemyId: "shield-heavy" },
        { x: 0, z: 18, enemyId: "marksman" },
      ],
      reactor: [
        { x: -14, z: -4, enemyId: "juggernaut" },
        { x: 14, z: -4, enemyId: "rifleman" },
        { x: 0, z: -6, enemyId: "marksman" },
      ],
      boss: [
        { x: 0, z: -28, enemyId: "boss-siege" },
        { x: -12, z: -22, enemyId: "rifleman" },
        { x: 12, z: -22, enemyId: "rusher" },
      ],
    },
    objectives: [
      {
        id: "breach",
        kind: "clear-zone",
        label: "Breach the outer chamber",
        description: "Force open the bunker entrance and clear the outer defense.",
        zone: { x: 0, z: 24 },
        radius: 12,
        spawnIds: ["breach"],
      },
      {
        id: "reactor",
        kind: "interact",
        label: "Lock reactor containment",
        description: "Stabilize the vault long enough to expose the core chamber.",
        zone: { x: 0, z: -6 },
        radius: 6,
        holdSeconds: 2.5,
        spawnIds: ["reactor"],
      },
      {
        id: "boss",
        kind: "boss",
        label: "Destroy the Siege Breaker",
        description: "Defeat the juggernaut prototype and collapse the vault command chain.",
        zone: { x: 0, z: -28 },
        radius: 10,
        bossId: "siege-breaker",
        spawnIds: ["boss"],
      },
      {
        id: "extract",
        kind: "extract",
        label: "Extract before collapse",
        description: "Reach the lift before the reactor cascade detonates.",
        zone: { x: 0, z: -40 },
        radius: 5,
      },
    ],
  },
];

export const survivalMaps: SurvivalMapDefinition[] = [
  {
    id: "dock-gauntlet",
    name: "Dock Gauntlet",
    basedOnMissionId: "dock-breach",
    theme: "urban",
    description: "A container yard choke with long exterior sightlines and close flank pressure.",
    playerSpawn: { x: 0, z: 26 },
    extractPoint: { x: 0, z: 26 },
  },
  {
    id: "foundry-pit",
    name: "Foundry Pit",
    basedOnMissionId: "foundry-blackout",
    theme: "industrial",
    description: "A furnace floor survival pit that mixes lanes with cover-heavy center pushes.",
    playerSpawn: { x: 0, z: 18 },
    extractPoint: { x: 0, z: 18 },
  },
  {
    id: "vault-core",
    name: "Vault Core",
    basedOnMissionId: "iron-vault",
    theme: "bunker",
    description: "A claustrophobic bunker reactor where elites arrive early and often.",
    playerSpawn: { x: 0, z: 22 },
    extractPoint: { x: 0, z: 22 },
  },
];
