import type { AttachmentDefinition } from "../../core/types/content";

export const attachments: AttachmentDefinition[] = [
  {
    id: "optic-red-dot",
    name: "Red Dot",
    slot: "optic",
    description: "Faster target acquisition with a cleaner sight picture.",
    unlockXp: 0,
    unlockCost: 0,
    modifiers: {
      adsSpread: -0.001,
      adsTime: -0.015,
    },
  },
  {
    id: "optic-holo",
    name: "Holo Sight",
    slot: "optic",
    description: "Improves stability while aiming under pressure.",
    unlockXp: 200,
    unlockCost: 120,
    modifiers: {
      adsSpread: -0.002,
      recoil: -0.08,
      adsTime: 0.01,
    },
  },
  {
    id: "optic-magnifier",
    name: "Magnifier",
    slot: "optic",
    description: "Extended reach at the cost of some movement feel.",
    unlockXp: 900,
    unlockCost: 260,
    modifiers: {
      range: 8,
      adsTime: 0.02,
      adsMoveSpeedMultiplier: -0.05,
    },
  },
  {
    id: "muzzle-suppressor",
    name: "Suppressor",
    slot: "muzzle",
    description: "Smooth recoil and tighter spread with lower punch.",
    unlockXp: 350,
    unlockCost: 140,
    modifiers: {
      recoil: -0.12,
      spread: -0.003,
      damage: -2,
    },
  },
  {
    id: "muzzle-compensator",
    name: "Compensator",
    slot: "muzzle",
    description: "Sharper recoil control for sustained fire.",
    unlockXp: 500,
    unlockCost: 180,
    modifiers: {
      recoil: -0.18,
      spread: -0.004,
      adsTime: 0.012,
    },
  },
  {
    id: "muzzle-breacher",
    name: "Breacher Choke",
    slot: "muzzle",
    description: "Shot-pack tightening for room clearing.",
    unlockXp: 650,
    unlockCost: 200,
    modifiers: {
      spread: -0.01,
      range: 2,
    },
  },
  {
    id: "mag-extended",
    name: "Extended Mag",
    slot: "magazine",
    description: "More rounds on tap with slower reloads.",
    unlockXp: 300,
    unlockCost: 150,
    modifiers: {
      magazineSize: 8,
      reloadTime: 0.18,
      moveSpeedMultiplier: -0.02,
    },
  },
  {
    id: "mag-fast",
    name: "Fast Mag",
    slot: "magazine",
    description: "Aggressive reload tuning for faster re-engagement.",
    unlockXp: 450,
    unlockCost: 180,
    modifiers: {
      reloadTime: -0.25,
      reserveAmmo: -8,
    },
  },
  {
    id: "mag-overpressure",
    name: "Overpressure Rounds",
    slot: "magazine",
    description: "Harder impact with more recoil and smaller reserve.",
    unlockXp: 1000,
    unlockCost: 280,
    modifiers: {
      damage: 5,
      recoil: 0.15,
      reserveAmmo: -18,
    },
  },
  {
    id: "handling-light-stock",
    name: "Light Stock",
    slot: "handling",
    description: "Improves strafe speed and snap aim response.",
    unlockXp: 150,
    unlockCost: 90,
    modifiers: {
      moveSpeedMultiplier: 0.05,
      adsTime: -0.018,
      recoil: 0.06,
    },
  },
  {
    id: "handling-heavy-stock",
    name: "Heavy Stock",
    slot: "handling",
    description: "Grounds recoil for more stable follow-up shots.",
    unlockXp: 550,
    unlockCost: 190,
    modifiers: {
      recoil: -0.2,
      moveSpeedMultiplier: -0.04,
      adsMoveSpeedMultiplier: -0.04,
    },
  },
  {
    id: "handling-laser",
    name: "Targeting Laser",
    slot: "handling",
    description: "Tighter hip-fire and faster close-range tracking.",
    unlockXp: 800,
    unlockCost: 240,
    modifiers: {
      spread: -0.004,
      adsTime: -0.01,
    },
  },
];
