import type { EnemyDefinition } from "../../core/types/content";

export const enemies: EnemyDefinition[] = [
  {
    id: "rifleman",
    name: "Rifleman",
    archetype: "rifleman",
    health: 90,
    moveSpeed: 4.2,
    preferredRange: 18,
    attackDamage: 9,
    attackCooldown: 0.9,
    rewardXp: 32,
    rewardCredits: 22,
    color: "#6ea6ff",
    scale: 1,
  },
  {
    id: "rusher",
    name: "Rusher",
    archetype: "rusher",
    health: 70,
    moveSpeed: 6.4,
    preferredRange: 4.5,
    attackDamage: 13,
    attackCooldown: 0.65,
    rewardXp: 38,
    rewardCredits: 26,
    color: "#ff9150",
    scale: 0.95,
  },
  {
    id: "marksman",
    name: "Marksman",
    archetype: "marksman",
    health: 80,
    moveSpeed: 3.7,
    preferredRange: 26,
    attackDamage: 16,
    attackCooldown: 1.6,
    rewardXp: 44,
    rewardCredits: 30,
    color: "#c1a6ff",
    scale: 1,
  },
  {
    id: "shield-heavy",
    name: "Shield Heavy",
    archetype: "shield-heavy",
    health: 180,
    moveSpeed: 2.8,
    preferredRange: 10,
    attackDamage: 12,
    attackCooldown: 1.25,
    rewardXp: 70,
    rewardCredits: 48,
    color: "#78f0c2",
    scale: 1.15,
    armorFrontMultiplier: 0.35,
  },
  {
    id: "juggernaut",
    name: "Juggernaut",
    archetype: "juggernaut",
    health: 420,
    moveSpeed: 2.2,
    preferredRange: 14,
    attackDamage: 22,
    attackCooldown: 1.8,
    rewardXp: 140,
    rewardCredits: 100,
    color: "#ff5f6d",
    scale: 1.35,
    armorFrontMultiplier: 0.55,
  },
  {
    id: "boss-commander",
    name: "Black Cell Commander",
    archetype: "boss-commander",
    health: 720,
    moveSpeed: 4.6,
    preferredRange: 20,
    attackDamage: 20,
    attackCooldown: 0.85,
    rewardXp: 220,
    rewardCredits: 160,
    color: "#ffe37e",
    scale: 1.05,
  },
  {
    id: "boss-siege",
    name: "Siege Juggernaut",
    archetype: "boss-siege",
    health: 1200,
    moveSpeed: 2.1,
    preferredRange: 16,
    attackDamage: 26,
    attackCooldown: 1.2,
    rewardXp: 400,
    rewardCredits: 300,
    color: "#ff4040",
    scale: 1.55,
    armorFrontMultiplier: 0.45,
  },
];
