import type { EquipmentDefinition, WeaponDefinition } from "../../core/types/content";

export const primaryWeapons: WeaponDefinition[] = [
  {
    id: "arx4",
    name: "ARX-4",
    category: "primary",
    archetype: "assault",
    description: "Balanced 5.56 platform with reliable recoil control.",
    unlockXp: 0,
    unlockCost: 0,
    accent: "#9ad7ff",
    slots: ["optic", "muzzle", "magazine", "handling"],
    stats: {
      damage: 26,
      fireRate: 9.2,
      magazineSize: 30,
      reserveAmmo: 150,
      reloadTime: 1.9,
      spread: 0.016,
      adsSpread: 0.005,
      range: 36,
      moveSpeedMultiplier: 1,
      adsMoveSpeedMultiplier: 0.86,
      adsTime: 0.18,
      recoil: 0.9,
    },
  },
  {
    id: "viper9",
    name: "Viper-9",
    category: "primary",
    archetype: "smg",
    description: "Fast compact SMG built for flanks and interior pushes.",
    unlockXp: 200,
    unlockCost: 180,
    accent: "#52ffd0",
    slots: ["optic", "muzzle", "magazine", "handling"],
    stats: {
      damage: 18,
      fireRate: 13.6,
      magazineSize: 34,
      reserveAmmo: 170,
      reloadTime: 1.65,
      spread: 0.022,
      adsSpread: 0.009,
      range: 24,
      moveSpeedMultiplier: 1.06,
      adsMoveSpeedMultiplier: 0.95,
      adsTime: 0.14,
      recoil: 1.1,
    },
  },
  {
    id: "breach12",
    name: "Breach-12",
    category: "primary",
    archetype: "shotgun",
    description: "Close-range breacher with devastating pellet spread.",
    unlockXp: 600,
    unlockCost: 320,
    accent: "#ffca85",
    slots: ["optic", "muzzle", "magazine", "handling"],
    stats: {
      damage: 11,
      fireRate: 1.35,
      magazineSize: 8,
      reserveAmmo: 48,
      reloadTime: 2.2,
      spread: 0.075,
      adsSpread: 0.055,
      range: 16,
      moveSpeedMultiplier: 0.97,
      adsMoveSpeedMultiplier: 0.78,
      adsTime: 0.2,
      recoil: 1.7,
      pellets: 8,
    },
  },
  {
    id: "sentinel",
    name: "Sentinel DMR",
    category: "primary",
    archetype: "dmr",
    description: "Precise semi-auto rifle for extended fights and bosses.",
    unlockXp: 1200,
    unlockCost: 520,
    accent: "#d9b8ff",
    slots: ["optic", "muzzle", "magazine", "handling"],
    stats: {
      damage: 54,
      fireRate: 2.7,
      magazineSize: 18,
      reserveAmmo: 90,
      reloadTime: 2.35,
      spread: 0.006,
      adsSpread: 0.002,
      range: 54,
      moveSpeedMultiplier: 0.94,
      adsMoveSpeedMultiplier: 0.74,
      adsTime: 0.22,
      recoil: 1.4,
    },
  },
];

export const secondaryWeapons: WeaponDefinition[] = [
  {
    id: "sidearm45",
    name: "Sidearm .45",
    category: "secondary",
    archetype: "pistol",
    description: "Reliable fallback sidearm with solid stopping power.",
    unlockXp: 0,
    unlockCost: 0,
    accent: "#efefef",
    slots: ["optic", "muzzle", "magazine", "handling"],
    stats: {
      damage: 28,
      fireRate: 4.1,
      magazineSize: 15,
      reserveAmmo: 75,
      reloadTime: 1.55,
      spread: 0.012,
      adsSpread: 0.004,
      range: 24,
      moveSpeedMultiplier: 1.04,
      adsMoveSpeedMultiplier: 0.92,
      adsTime: 0.12,
      recoil: 0.8,
    },
  },
  {
    id: "stinger",
    name: "Stinger Auto",
    category: "secondary",
    archetype: "pistol",
    description: "Machine pistol for emergency close-range dumps.",
    unlockXp: 500,
    unlockCost: 260,
    accent: "#ff8f8f",
    slots: ["optic", "muzzle", "magazine", "handling"],
    stats: {
      damage: 15,
      fireRate: 16,
      magazineSize: 24,
      reserveAmmo: 120,
      reloadTime: 1.6,
      spread: 0.026,
      adsSpread: 0.012,
      range: 18,
      moveSpeedMultiplier: 1.08,
      adsMoveSpeedMultiplier: 0.96,
      adsTime: 0.11,
      recoil: 1.25,
    },
  },
];

export const tacticalEquipment: EquipmentDefinition[] = [
  {
    id: "stim",
    name: "Stim Injector",
    category: "tactical",
    description: "Instantly restore health and gain a short speed burst.",
    unlockXp: 0,
    unlockCost: 0,
    cooldown: 18,
    charges: 2,
  },
  {
    id: "flash",
    name: "Flash Charge",
    category: "tactical",
    description: "Stuns and slows enemies in a compact radius.",
    unlockXp: 450,
    unlockCost: 220,
    cooldown: 15,
    charges: 2,
  },
];

export const lethalEquipment: EquipmentDefinition[] = [
  {
    id: "frag",
    name: "Fragmentation Grenade",
    category: "lethal",
    description: "Short fuse grenade for burst area damage.",
    unlockXp: 0,
    unlockCost: 0,
    cooldown: 20,
    charges: 2,
  },
  {
    id: "incendiary",
    name: "Incendiary",
    category: "lethal",
    description: "Creates a temporary burning denial zone.",
    unlockXp: 900,
    unlockCost: 340,
    cooldown: 24,
    charges: 2,
  },
];

export const allWeapons = [...primaryWeapons, ...secondaryWeapons];
export const allEquipment = [...tacticalEquipment, ...lethalEquipment];
